HastaTakip/Controllers/VitalSignMeasurementController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using HastaTakip.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HastaTakip.Helper;
using Quartz;
using Quartz.Impl;

namespace HastaTakip.Controllers
{
    public class VitalSignMeasurementController : Controller
    {

        VitalSignMeasurementManager vsmm = new VitalSignMeasurementManager(new EfVitalSignMeasurementValueDal());
        PatientManager pm = new PatientManager(new EfPatientDal());

        public ActionResult VitalSignByPatient(int id)
        {
            ViewBag.id = id;
            TempData["id"] = id;
            
                //son bulgular                
                ViewBag.sonsolunum = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 9).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();
                ViewBag.sonates = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 1).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();
                ViewBag.sonsistolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 4).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();
                ViewBag.sondiastolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 8).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();
                ViewBag.sonnabız = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 10).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();
                ViewBag.sonkansekeri = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 11).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();
                ViewBag.sonoksijen = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 12).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();

                //son tarihler
                ViewBag.sonsolunumtarih = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 9).Select(y => y.OlcumZamani).DefaultIfEmpty().Last();
                ViewBag.sonatestarih = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 1).Select(y => y.OlcumZamani).DefaultIfEmpty().Last();
                ViewBag.sonsistoliktarih = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 4).Select(y => y.OlcumZamani).DefaultIfEmpty().Last();
                ViewBag.sondiastoliktarih = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 8).Select(y => y.OlcumZamani).DefaultIfEmpty().Last();
                ViewBag.sonnabıztarih = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 10).Select(y => y.OlcumZamani).DefaultIfEmpty().Last();
                ViewBag.sonkansekeritarih = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 11).Select(y => y.OlcumZamani).DefaultIfEmpty().Last();
                ViewBag.sonoksijentarih = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 12).Select(y => y.OlcumZamani).DefaultIfEmpty().Last();
                
                //son 10 gün min değer
                ViewBag.son10minsolunum = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 9 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son10minates = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 1 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son10minsistolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 4 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son10mindiastolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 8 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son10minnabız = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 10 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son10minkansekeri = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 11 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son10minoksijen = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 12 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();

                //son 10 gün max değer
                ViewBag.son10maxsolunum = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 9 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son10maxates = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 1 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son10maxsistolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 4 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son10maxdiastolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 8 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son10maxnabız = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 10 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son10maxkansekeri = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 11 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son10maxoksijen = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 12 && x.OlcumZamani.AddDays(10) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                 
                //son 1 gün min değer
                ViewBag.son1minsolunum = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 9 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son1minates = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 1 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son1minsistolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 4 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son1mindiastolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 8 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son1minnabız = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 10 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son1minkansekeri = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 11 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();
                ViewBag.son1minoksijen = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 12 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Min();

                //son 1 gün max değer
                ViewBag.son1maxsolunum = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 9 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son1maxates = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 1 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son1maxsistolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 4 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son1maxdiastolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 8 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son1maxnabız = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 10 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son1maxkansekeri = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 11 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
                ViewBag.son1maxoksijen = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 12 && x.OlcumZamani.AddDays(1) >= DateTime.Now).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Max();
  
            var vitalsignvalues = vsmm.GetListByPatient(id);
            return View(vitalsignvalues);
        }

        public ActionResult AdminVitalSignByPatient(int id)
        {
            ViewBag.id = id;
            TempData["id"] = id;

            //son bulgular                
            ViewBag.sonsolunum = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 9).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();
            ViewBag.sonates = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 1).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();
            ViewBag.sonsistolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 4).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();
            ViewBag.sondiastolik = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 8).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();
            ViewBag.sonnabız = vsmm.GetList().Where(x => x.HastaID == id && x.VitalBulguID == 10).Select(y => y.OlcumDeğeri).DefaultIfEmpty().Last();

HastaTakip/Views/VitalSignMeasurement/AddVitalSign.cshtml
@model EntityLayer.Concrete.VitalSignMeasurementValue
@{
    ViewBag.Title = "AddVitalSign";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Main content -->
    <section class="content">
        <div class="row-1">
            <div class="col-md-6">
                <br />
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Hasta Kayıt</h3>
                    </div>
                    @using (Html.BeginForm("AddVitalSign", "VitalSignMeasurement", FormMethod.Post))
                    {
                        <div class="card-body">
                            <div class="form-group">
                                @Html.Label("Hasta ID")
                                @Html.TextBoxFor(x => x.HastaID, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                @Html.Label("Vital Bulgu")
                                @Html.TextBoxFor(x => x.VitalBulguID, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                @Html.Label("Ölçüm Değeri")
                                @Html.TextBoxFor(x => x.OlcumDeğeri, new { @class = "form-control" })
                            </div>                           
                            <div class="col-12">
                                <button class="btn btn-success float-right">Ekle</button>
                                <br />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

</body>
</html>

HastaTakip/Views/VitalSignMeasurement/AdminAtes.cshtml
@{
    ViewBag.Title = "AdminAtes";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
@Scripts.Render("~/bundles/jquery")
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<figure class="highcharts-figure">
    <div id="container"></div>
</figure>
<link href="~/Grafik/Grafik.css" rel="stylesheet" />
<script>
    $(document).ready(function () {
        $.getJSON("/VitalSignMeasurement/GetAtes/@TempData["id"]", function (data) {
            var deger = []
            var date = []

            for (var i = 0; i < data.length; i++) {
                deger.push(data[i].olcum);
                date.push(data[i].tarih);
            }

            Highcharts.chart('container', {
                chart: {
                    type: 'line'
                },
                title: {
                    text: 'Ateş Ölçümleri'
                },
                xAxis: {
                    categories: date
                },
                yAxis: {
                    title: {
                        text: 'Derece (°C)'
                    },
                    plotLines: [{
                        id: 'limit-min',
                        color: '#FF0000',
                        dashStyle: 'ShortDash',
                        width: 2,
                        value: 36,
                        zIndex: 0

                    }]
                },
                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                        enableMouseTracking: false
                    }
                },
                series: [{
                    name: 'Ateş',
                    data: deger
                }]

            });
        });
    });
</script>

HastaTakip/Views/VitalSignMeasurement/AdminDiaTan.cshtml
@{
    ViewBag.Title = "AdminDiaTan";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
@Scripts.Render("~/bundles/jquery")
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<figure class="highcharts-figure">
    <div id="container2"></div>
</figure>
<link href="~/Grafik/Grafik.css" rel="stylesheet" />
<script>
    $(document).ready(function () {
        $.getJSON("/VitalSignMeasurement/GetDiaTan/@TempData["id"]", function (data) {
            var deger = []
            var date = []

            for (var i = 0; i < data.length; i++) {
                deger.push(data[i].olcum);
                date.push(data[i].tarih);
            }

            Highcharts.chart('container2', {
                chart: {
                    type: 'line'
                },
                title: {
                    text: 'Diastolik Tansiyon'
                },
                xAxis: {
                    categories: date
                },
                yAxis: {
                    title: {
                        text: 'Diastolik Tansiyon(mm/Hg)'
                    },
                    plotLines: [{
                        id: 'limit-min',
                        color: '#FF0000',
                        dashStyle: 'ShortDash',
                        width: 2,
                        value: 60,
                        zIndex: 0
                    }, {
                        id: 'limit-max',
                        color: '#008000',
                        dashStyle: 'ShortDash',
                        width: 2,
                        value: 85,
                        zIndex: 0
                    }]
                },
                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                        enableMouseTracking: false
                    }
                },
                series: [{
                    name: 'Diastolik Tansiyon',
                    data: deger
                }]

            });
        });
    });
</script>

HastaTakip/Views/VitalSignMeasurement/AdminSisTan.cshtml
@{
    ViewBag.Title = "AdminSisTan";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
@Scripts.Render("~/bundles/jquery")
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<figure class="highcharts-figure">
    <div id="container1"></div>
</figure>
<link href="~/Grafik/Grafik.css" rel="stylesheet" />

<script>
    $(document).ready(function () {
        $.getJSON("/VitalSignMeasurement/GetSisTan/@TempData["id"]", function (data) {
            var deger = []
            var date = []
            for (var i = 0; i < data.length; i++) {
                deger.push(data[i].olcum);
                date.push(data[i].tarih);
            }

            Highcharts.chart('container1', {
                chart: {
                    type: 'line'
                },
                title: {
                    text: 'Sistolik Tansiyon Ölçümleri'
                },
                xAxis: {
                    categories: date
                },
                yAxis: {
                    title: {
                        text: 'Sistolik Tansiyon(mm/Hg)'
                    },
                    plotLines: [{
                        id: 'limit-min',
                        color: '#FF0000',
                        dashStyle: 'ShortDash',
                        width: 2,
                        value: 90,
                        zIndex: 0
                    }, {
                        id: 'limit-max',
                        color: '#008000',
                        dashStyle: 'ShortDash',
                        width: 2,
                        value: 150,
                        zIndex: 0
                    }]
                },
                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                        enableMouseTracking: false
                    }
                },
                series: [{
                    name: 'Sistolik Tansiyon',
                    data: deger
                }]

            });
        });
    });
</script>

HastaTakip/Views/VitalSignMeasurement/AdminSolunum.cshtml
@{
    ViewBag.Title = "AdminSolunum";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
@Scripts.Render("~/bundles/jquery")
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<figure class="highcharts-figure">
    <div id="container3"></div>
</figure>
<link href="~/Grafik/Grafik.css" rel="stylesheet" />
<script>
    $(document).ready(function () {
        $.getJSON("/VitalSignMeasurement/GetSolunum/@TempData["id"]", function (data) {
            var deger = []
            var date = []
            var min = 90;

            for (var i = 0; i < data.length; i++) {
                deger.push(data[i].olcum);
                date.push(data[i].tarih);
            }

            Highcharts.chart('container3', {
                chart: {
                    type: 'line'
                },
                title: {
                    text: 'Solunum Ölçümleri'
                },
                xAxis: {
                    categories: date,
                    line: min
                },
                yAxis: {
                    title: {
                        text: 'Solunum(br/min)'
                    },
                    plotLines: [{
                        id: 'limit-min',
                        color: '#FF0000',
                        dashStyle: 'ShortDash',
                        width: 2,
                        value: 15,
                        zIndex: 0
                    }, {
                        id: 'limit-max',
                        color: '#008000',
                        dashStyle: 'ShortDash',
                        width: 2,
                        value: 35,
                        zIndex: 0
                    }]
                },
                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                        enableMouseTracking: false
                    }
                },
                series: [{
                    name: 'Solunum',
                    data: deger
                }]

            });
        });
    });
</script>

HastaTakip/Views/VitalSignMeasurement/AdminVitalSignByPatient.cshtml
@{
    ViewBag.Title = "AdminVitalSignByPatient";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Hasta Vital Bulgu Değerleri</h1>
                </div>
            </div>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                    <tr>
                                        <th>Vital Bulgu</th>
                                        <th>Son</th>
                                        <th><center>Tarih</center></th>
                                        <th><center>Son 10 Gün(min-maks)</center></th>
                                        <th><center>Son 24 Saat(min-maks)</center></th>
                                    </tr>
                                </thead>
                                <tbody>

                                    <tr>
                                        <td>Solunum(br/min)</td>
                                        <td>@ViewBag.sonsolunum</td>
                                        <td><center>@ViewBag.sonsolunumtarih</center></td>
                                        <td><center>@ViewBag.son10minsolunum-@ViewBag.son10maxsolunum</center></td>
                                        <td><center>@ViewBag.son1minsolunum-@ViewBag.son1maxsolunum</center></td>

                                    </tr>
                                    <tr>
                                        <td>Ateş(°C)</td>
                                        <td>@ViewBag.sonates</td>
                                        <td><center>@ViewBag.sonatestarih</center></td>
                                        <td><center>@ViewBag.son10minates-@ViewBag.son10maxates</center></td>
                                        <td><center>@ViewBag.son1minates-@ViewBag.son1maxates</center></td>

                                    </tr>
                                    <tr>
                                        <td>Sistolik Tansiyon(mm/Hg)</td>
                                        <td>@ViewBag.sonsistolik</td>
                                        <td><center>@ViewBag.sonsistoliktarih</center></td>
                                        <td><center>@ViewBag.son10minsistolik-@ViewBag.son10maxsistolik</center></td>
                                        <td><center>@ViewBag.son1minsistolik-@ViewBag.son1maxsistolik</center></td>
                                    </tr>
                                    <tr>
                                        <td>Diastolik Tansiyon(mm/Hg)</td>
                                        <td>@ViewBag.sondiastolik</td>
                                        <td><center>@ViewBag.sondiastoliktarih</center></td>
                                        <td><center>@ViewBag.son10mindiastolik-@ViewBag.son10maxdiastolik</center></td>
                                        <td><center>@ViewBag.son1mindiastolik-@ViewBag.son1maxdiastolik</center></td>
                                    </tr>
                                    <tr>
                                        <td>Nabız(bpm)</td>
                                        <td>@ViewBag.sonnabız</td>
                                        <td><center>@ViewBag.sonnabıztarih</center></td>
                                        <td><center>@ViewBag.son10minnabız-@ViewBag.son10maxnabız</center></td>
                                        <td><center>@ViewBag.son1minnabız-@ViewBag.son1maxnabız</center></td>
                                    </tr>
                                    <tr>
                                        <td>Kan Şekeri(Stick)(mg/dl)</td>
                                        <td>@ViewBag.sonkansekeri</td>
                                        <td><center>@ViewBag.sonkansekeritarih</center></td>
                                        <td><center>@ViewBag.son10minkansekeri-@ViewBag.son10maxkansekeri</center></td>
                                        <td><center>@ViewBag.son1minkansekeri-@ViewBag.son1maxkansekeri</center></td>
                                    </tr>
                                    <tr>
                                        <td>Oksijen Saturasyon Takibi(%)</td>
                                        <td>@ViewBag.sonoksijen</td>
                                        <td><center>@ViewBag.sonoksijentarih</center></td>
                                        <td><center>@ViewBag.son10minoksijen-@ViewBag.son10maxoksijen</center></td>
                                        <td><center>@ViewBag.son1minoksijen-@ViewBag.son1maxoksijen</center></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>
<div class="row">
    <div class="col-10">
        <a href="/VitalSignMeasurement/AdminSisTan/@ViewBag.id" class="btn btn-primary">Sistolik tansiyon Grafik</a>
        <a href="/VitalSignMeasurement/AdminAtes/@ViewBag.id" class="btn btn-primary">Ateş Grafik</a>
        <a href="/VitalSignMeasurement/AdminDiaTan/@ViewBag.id" class="btn btn-primary">Diastolik Tansiyon Grafik</a>
        <a href="/VitalSignMeasurement/AdminSolunum/@ViewBag.id" class="btn btn-primary">Solunum Grafik</a>
    </div>
    <div class="col-2">
        <a href="/VitalSignMeasurement/AddVitalSignAll/@ViewBag.id" class="btn btn-success">Makineye Bağla</a>
    </div>
</div>

HastaTakip/Views/VitalSignMeasurement/Ates.cshtml
@{
    ViewBag.Title = "Grafikler";
    Layout = "~/Views/Shared/_DoctorLayout.cshtml";
}

<br />
@Scripts.Render("~/bundles/jquery")
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<figure class="highcharts-figure">
    <div id="container"></div>
</figure>
<link href="~/Grafik/Grafik.css" rel="stylesheet" />
<script>
    $(document).ready(function () {
        $.getJSON("/VitalSignMeasurement/GetAtes/@TempData["id"]", function (data) {
            var deger = []
            var date = []

            for (var i = 0; i < data.length; i++) {
                deger.push(data[i].olcum);
                date.push(data[i].tarih);
            }

            Highcharts.chart('container', {
                chart: {
                    type: 'line'
                },
                title: {
                    text: 'Ateş Ölçümleri'
                },
                xAxis: {
                    categories: date
                },
                yAxis: {
                    title: {
                        text: 'Derece (°C)'
                    },
                    plotLines: [{
                        id: 'limit-min',
                        color: '#FF0000',
                        dashStyle: 'ShortDash',
                        width: 2,
                        value: 36,
                        zIndex: 0
                    
                    }]
                },
                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                        enableMouseTracking: false
                    }
                },
                series: [{
                    name: 'Ateş',
                    data: deger
                }]

            });
        });
    });
</script>