HastaTakip/Controllers/PatientArrivalController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using HastaTakip.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HastaTakip.Controllers
{
    public class PatientArrivalController : Controller
    {
        PatientArrivalManager pam = new PatientArrivalManager(new EfPatientArrivalDal());
        PatientManager pm = new PatientManager(new EfPatientDal());
        DoctorManager dm = new DoctorManager(new EfDoctorDal());

        public ActionResult Index(int p = 1)
        {
            var PatientArrivalValues = pam.GetList().ToPagedList(p, 6); ;
            return View(PatientArrivalValues);
        }

        [HttpGet]
        public ActionResult AddPatientArrival(int id)
        {
            Context db = new Context();
            ViewBag.Servisler = db.Services.ToList().Select(x => new SelectListItem { Text = x.ServisAdi, Value = x.ServisID.ToString() }).ToList();
            ViewBag.Doktorlar = db.Doctors.ToList().Select(x => new SelectListItem { Text = x.Ad + " " + x.Soyad, Value = x.DoktorID.ToString() }).ToList();

            PatientArrival patientArrival = new PatientArrival();
            var hasta = pm.GetByID(id);
            patientArrival.HastaID = hasta.HastaID;
            return View(patientArrival);


        }

        [HttpPost]
        public ActionResult AddPatientArrival(PatientArrival p)
        {
            p.GirisTarihi = DateTime.Parse(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss"));
            p.Status = true;
            pam.PatientArrivalAdd(p);
            return RedirectToAction("Index");

        }
            
        public ActionResult ExitPatient(int id)
        {
            var PatientArrivalValue = pam.GetByID(id);      
            PatientArrivalValue.CıkısTarihi = DateTime.Parse(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss"));
            PatientArrivalValue.Status = false;
            pam.PatientArrivalUpdate(PatientArrivalValue);  
            return RedirectToAction("Index");
        }   
        
    }
}

HastaTakip/Views/PatientArrival/AddPatientArrival.cshtml
@model EntityLayer.Concrete.PatientArrival
@{
    ViewBag.Title = "AddPatientArrival";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Main content -->
    <section class="content">
        <div class="row-1">
            <div class="col-md-6">
                <br />
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Hasta Geliş</h3>
                    </div>
                    
                    @using (Html.BeginForm("AddPatientArrival", "PatientArrival", FormMethod.Post))
                    {
                        <div class="card-body">
                            <div class="form-group">
                                @Html.HiddenFor(x =>x.HastaID)                                
                            </div>
                            <div class="form-group">                              
                                @Html.Label("Servis")
                                @Html.DropDownListFor(x=>x.ServisID,(List<SelectListItem>)ViewBag.Servisler, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                @Html.Label("Doktor")
                                @Html.DropDownListFor(x=>x.DoktorID,(List<SelectListItem>)ViewBag.Doktorlar, new { @class = "form-control" })
                            </div>                           
                            <div class="col-12">
                                <button class="btn btn-success float-right">Ekle</button>
                                <br />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

</body>
</html>

HastaTakip/Views/PatientArrival/Index.cshtml
@using EntityLayer.Concrete
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<PatientArrival>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Hasta Gelişleri</h1>
                </div>
            </div>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                    <tr>
                                        <th>TC</th>
                                        <th>Hasta Adı</th>
                                        <th>Giriş Tarihi</th>
                                        <th>Çıkış Tarihi</th>
                                        <th>Servis</th>
                                        <th>Doktor</th>
                                        <th>Hasta Çıkışı</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Patient.TC</td>
                                            <td>@item.Patient.Ad @item.Patient.Soyad</td>
                                            <td>@item.GirisTarihi.ToString("dd/MM/yyyy HH:mm")</td>
                                            <td>@item.CıkısTarihi</td>
                                            <td>@item.Service.ServisAdi</td>
                                            <td>@item.Doctor.Ad @item.Doctor.Soyad</td>
                                            @if (item.CıkısTarihi == null)
                                            {
                                                <td><a href="/PatientArrival/ExitPatient/@item.HastaGelisiID" class="btn btn-danger">Hasta Çıkış Yap</a></td>

                                            }
                                            else
                                            {
                                                <td><button class="btn btn-info">Hasta Çıkışı Yapıldı</button></td>

                                            }
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>
<div class="col-12">
    <div class="align-content-lg-center">
        @Html.PagedListPager((IPagedList)Model, p => Url.Action("Index", new { p }), new PagedListRenderOptions
        {
        LiElementClasses = new List<string>
        { "page-link"}
        })
    </div>
</div>