HastaTakip/Controllers/AdminPatientController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace HastaTakip.Controllers
{
    public class AdminPatientController : Controller
    {
        PatientManager cm = new PatientManager(new EfPatientDal());        
        [Authorize]
        public ActionResult Index(int p = 1)
        {
            var patientvalues = cm.GetPatients().ToPagedList(p,6);
            return View(patientvalues);
        }

        
        [HttpGet]
        public ActionResult AddPatient()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddPatient(Patient p)
        {
            PatientValidator patientvalidator = new PatientValidator();
            ValidationResult result = patientvalidator.Validate(p);
            p.Status = true;

            if (result.IsValid)
            {
                cm.PatientAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return View();
        }
      
        [HttpGet]
        public ActionResult EditPatient(int id)
        {
            var patientvalue = cm.GetByID(id);
            return View(patientvalue);

        }
       
        [HttpPost]
        public ActionResult EditPatient(Patient p)
        {
            PaitentUpdateValidator patientupdatevalidator = new PaitentUpdateValidator();
            ValidationResult result = patientupdatevalidator.Validate(p);

            if (result.IsValid)
            {
                cm.PatientUpdate(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return View();
        }
    }
}

HastaTakip/Views/AdminPatient/AddPatient.cshtml
@model EntityLayer.Concrete.Patient
@{
    ViewBag.Title = "AddPatient";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

            <!-- Main content -->
            <section class="content">
                <div class="row-1">
                    <div class="col-md-6">
                        <br />
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Hasta Kayıt</h3>
                            </div>
                            @using (Html.BeginForm("AddPatient", "AdminPatient", FormMethod.Post))
                            {
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.Label("Hasta TC")
                                    @Html.TextBoxFor(x => x.TC, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.TC)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Hasta Ad")
                                    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Ad)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Hasta Soyad")
                                    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Soyad)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Hasta Doğum Tarihi")
                                    @Html.TextBoxFor(x => x.DogumTarihi, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.DogumTarihi)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Hasta Cinsiyet")
                                    @Html.DropDownListFor(x => x.Cinsiyet, new List<SelectListItem> {
                                        new SelectListItem() {Text="Erkek",Value="Erkek" ,},
                                        new SelectListItem() {Text="Kadın",Value="Kadın" },
                                    }, "Cinsiyet")
                                    @Html.ValidationMessageFor(x => x.Cinsiyet)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Hasta Adres")
                                    @Html.TextAreaFor(x => x.Adres, 5, 60, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Adres)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Hasta Telefon Numarası")
                                    @Html.TextBoxFor(x => x.Tel, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Tel)
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-success float-right">Ekle</button>
                                    <br />
                                </div>
                            </div>
                            }
                        </div>
                    </div>
                </div>
            </section>
      
</body>
</html>

HastaTakip/Views/AdminPatient/EditPatient.cshtml
@model EntityLayer.Concrete.Patient
@{
    ViewBag.Title = "EditPatient";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Main content -->
    <section class="content">
        <div class="row-1">
            <div class="col-md-6">
                <br />
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Hasta Güncelleme</h3>
                    </div>
                    @using (Html.BeginForm("EditPatient", "AdminPatient", FormMethod.Post))
                    {
                        <div class="card-body">
                            <div class="form-group">
                                @Html.HiddenFor(x => x.HastaID)
                            </div>
                            <div class="form-group">
                                @Html.Label("Hasta TC")
                                @Html.TextBoxFor(x => x.TC, new { @class = "form-control disabled",@readonly = true })
                            </div>
                            <div class="form-group">
                                @Html.Label("Hasta Ad")
                                @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Ad)
                            </div>
                            <div class="form-group">
                                @Html.Label("Hasta Soyad")
                                @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Soyad)
                            </div>
                            <div class="form-group">
                                @Html.Label("Hasta Doğum Tarihi")
                                @Html.TextBoxFor(x => x.DogumTarihi, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.DogumTarihi)
                            </div>
                            <div class="form-group">
                                @Html.Label("Hasta Cinsiyet")
                                @Html.DropDownListFor(x => x.Cinsiyet, new List<SelectListItem> {
                                    new SelectListItem() {Text="Erkek",Value="Erkek" ,},
                                    new SelectListItem() {Text="Kadın",Value="Kadın" },
                                }, "Cinsiyet")
                                @Html.ValidationMessageFor(x => x.Cinsiyet)
                            </div>
                            <div class="form-group">
                                @Html.Label("Hasta Adres")
                                @Html.TextAreaFor(x => x.Adres, 5, 60, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Adres)
                            </div>
                            <div class="form-group">
                                @Html.Label("Hasta Telefon Numarası")
                                @Html.TextBoxFor(x => x.Tel, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Tel)
                            </div>
                            <div class="col-12">
                                <button class="btn btn-success float-right">Kaydet</button>
                                <br />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

</body>
</html>

HastaTakip/Views/AdminPatient/Index.cshtml
@using EntityLayer.Concrete
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<Patient>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Hasta Listesi</h1>
                </div>
            </div>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                    <tr>
                                        <th>TC</th>
                                        <th>Ad</th>
                                        <th>Soyad</th>
                                        <th>Doğum Tarihi</th>
                                        <th>Cinsiyet</th>
                                        <th>Adres</th>
                                        <th>Tel</th>
                                        <th>Güncelle</th>
                                        <th>Hasta Gelişi</th>
                                        <th>Hasta Değerleri</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.TC</td>
                                            <td>@item.Ad</td>
                                            <td>@item.Soyad</td>
                                            <td>@item.DogumTarihi</td>
                                            <td>@item.Cinsiyet</td>
                                            <td>@item.Adres</td>
                                            <td>@item.Tel</td>
                                            <td><a href="/AdminPatient/EditPatient/@item.HastaID" class="btn btn-warning">Güncelle</a></td>
                                            <td><a href="/PatientArrival/AddPatientArrival/@item.HastaID" class="btn btn-primary">Hasta Gelişi Ekle</a></td>
                                            <td><a href="/VitalSignMeasurement/AdminVitalSignByPatient/@item.HastaID" class="btn btn-success">VB Değerleri</a></td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <a href="/AdminPatient/AddPatient" class="btn btn-info">Hasta Ekle</a>
                        </div>
                        <div>
                            @Html.PagedListPager((IPagedList)Model, p => Url.Action("Index", new { p }), new PagedListRenderOptions
                            {
                            LiElementClasses = new List<string>
                            { "page-link"}
                            })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>